### ISSUE TITLE
When to release the code

### ISSUE THREAD

**Issue by 11710615** [NarcissusEx/CuNeRF#1]
Thanks for the excellent work for applying nerf on medical image reconstruction. Whether it is convenient to determine the code releasing time. 
And I have one question about the rendering. In nerf, it has specific imaging meaning to render the pixel intensity along the ray. However, for  mri recontruction, rendering seems  meaningless. How to understand it.
Thanks for your rely in advance..

**Comment by NarcissusEx** [comment]
Thanks for your attentions! Unfortunately, the code will be released before December because I am a little bit busy right now. I apologize for taking so long to release the code.
In my opinion, NeRF is to build a continuous function based on the discrete-sampled measurements. However, this CT imaging-like rendering strategy (ray casting) can only build the continuity between views (e.g., continuous sinograms). Inspired by NeRF, our CuNeRF aims to build the continuous representation between voxels using a more reasonable rendering strategy. Since the rendering is based on the image continuity but not the simulation of a specific physical process, it can be used in medical volumetric data with different modalities.

**Comment by william2ai** [comment]
> Thanks for your attentions! Unfortunately, the code will be released before December because I am a little bit busy right now. I apologize for taking so long to release the code. In my opinion, NeRF is to build a continuous function based on the discrete-sampled measurements. However, this CT imaging-like rendering strategy (ray casting) can only build the continuity between views (e.g., continuous sinograms). Inspired by NeRF, our CuNeRF aims to build the continuous representation between voxels using a more reasonable rendering strategy. Since the rendering is based on the image continuity but not the simulation of a specific physical process, it can be used in medical volumetric data with different modalities.

When will it be released btw

**Comment by EugeneCh1a** [comment]
> Thanks for your attentions! Unfortunately, the code will be released before December because I am a little bit busy right now. I apologize for taking so long to release the code. In my opinion, NeRF is to build a continuous function based on the discrete-sampled measurements. However, this CT imaging-like rendering strategy (ray casting) can only build the continuity between views (e.g., continuous sinograms). Inspired by NeRF, our CuNeRF aims to build the continuous representation between voxels using a more reasonable rendering strategy. Since the rendering is based on the image continuity but not the simulation of a specific physical process, it can be used in medical volumetric data with different modalities.

When will it be released btw @NarcissusEx

**Comment by NarcissusEx** [comment]
Sorry for the delay, we have released the code now.
